### ISSUE TITLE
リコメンドの画面を作成する.

### ISSUE THREAD

**Issue by shinya-tan** [shinya-tan/purepure#6]

**Comment by eiyuuo** [comment]
マイナースポットの画面に入れる情報
次に表示するマップの条件を選ぶ
- 周辺のマイナースポット(自分の位置情報の近く)
- 別の地域のマイナースポット(那覇、宜野湾のマイナースポットなど)

**Comment by eiyuuo** [comment]
目的地が決まっていない他人のためにアプリが目的地を決めてくれるこのアプリの一番重要な機能
マイナー画面から変更した
